---
apiVersion: v1
kind: Service
metadata:
  name: ismyl-spa-customer-service-api
  labels:
    run: ismyl-spring-spa
spec:
  type: NodePort
  ports:
    - port: 3001
      protocol: TCP
  selector:
    run: ismyl-spring-spa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ismyl-spa-customer-service-api
  labels:
    app: ismyl-spring-spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ismyl-spring-spa
  template:
    metadata:
      labels:
        app: ismyl-spring-spa
    spec:
      containers:
        - name: ismyl-spring-spa-customer-service
          image: ismylawn/spring-customer-service
          imagePullPolicy: Always
          name: ismyl-spa-customer-service-api
          ports:
          - containerPort: 3001
