spring:
  application:
    name: gateway-service
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
zuul:
  routes:
    customers:
      path: /customers/**
      serviceId: customer-service
    orders:
      path: /orders/**
      serviceId: order-service
